# Generated by Django 5.2.8 on 2025-11-23 17:27

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_file', cloudinary.models.CloudinaryField(help_text='Receipt file (PDF or image)', max_length=255, verbose_name='receipt')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when receipt was uploaded')),
                ('validation_status', models.CharField(choices=[('PENDING', 'Pending Validation'), ('MATCHED', 'Matched'), ('DISCREPANCY', 'Has Discrepancies'), ('APPROVED', 'Approved by Finance')], default='PENDING', help_text='Validation status of the receipt', max_length=20)),
                ('extracted_receipt_data', models.JSONField(blank=True, help_text='Data extracted from receipt by AI (vendor, items, amounts)', null=True)),
                ('discrepancies', models.JSONField(blank=True, help_text='List of discrepancies found between receipt and PO', null=True)),
                ('finance_comments', models.TextField(blank=True, help_text='Comments from finance team')),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp when receipt was approved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Finance user who approved despite discrepancies', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_receipts', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(help_text='Associated purchase order', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='purchase_orders.purchaseorder')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'receipts',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['purchase_order'], name='receipts_purchas_dc136a_idx'), models.Index(fields=['validation_status'], name='receipts_validat_31449c_idx'), models.Index(fields=['-uploaded_at'], name='receipts_uploade_2e793a_idx')],
            },
        ),
    ]
