# Generated by Django 4.2.26 on 2025-11-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('APPROVER_L1', 'Approver Level 1'), ('APPROVER_L2', 'Approver Level 2'), ('FINANCE', 'Finance'), ('ADMIN', 'Administrator')], default='STAFF', max_length=20),
        ),
    ]
