# Generated by Django 5.2.8 on 2025-11-22 20:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='document_file',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload invoice/receipt PDF or image', max_length=255, null=True, verbose_name='document'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='document_processed',
            field=models.BooleanField(default=False, help_text='Whether document has been processed by AI'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='extracted_data',
            field=models.JSONField(blank=True, help_text='AI-extracted data from uploaded document', null=True),
        ),
    ]
