# Generated by Django 5.2.8 on 2025-11-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_requests', '0002_purchaserequest_document_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='vendor_name',
            field=models.CharField(blank=True, default='', help_text='Name of the vendor/supplier', max_length=255),
        ),
    ]
