# Generated by Django 5.2.8 on 2025-11-24 11:08

from django.db import migrations, models


def migrate_completed_to_approved(apps, schema_editor):
    """Migrate existing COMPLETED status records to APPROVED"""
    PurchaseRequest = apps.get_model('purchase_requests', 'PurchaseRequest')
    PurchaseRequest.objects.filter(status='COMPLETED').update(status='APPROVED')


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_requests', '0003_purchaserequest_vendor_name'),
    ]

    operations = [
        migrations.RunPython(migrate_completed_to_approved, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED_L1', 'Approved Level 1'), ('APPROVED_L2', 'Approved Level 2'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
    ]
