# Generated by Django 5.2.8 on 2025-11-24 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('REQUEST_SUBMITTED', 'Request Submitted'), ('REQUEST_APPROVED_L1', 'Request Approved (Level 1)'), ('REQUEST_APPROVED_L2', 'Request Approved (Level 2)'), ('REQUEST_APPROVED', 'Request Fully Approved'), ('REQUEST_REJECTED', 'Request Rejected'), ('PO_GENERATED', 'Purchase Order Generated'), ('RECEIPT_UPLOADED', 'Receipt Uploaded'), ('RECEIPT_VALIDATED', 'Receipt Validated'), ('PENDING_APPROVAL_L1', 'Pending Your Approval (Level 1)'), ('PENDING_APPROVAL_L2', 'Pending Your Approval (Level 2)')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='URL to navigate to when clicked', max_length=500, null=True)),
                ('request_id', models.IntegerField(blank=True, null=True)),
                ('po_id', models.IntegerField(blank=True, null=True)),
                ('receipt_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_notifi_user_id_aa782d_idx'), models.Index(fields=['user', 'is_read'], name='user_notifi_user_id_71ef9a_idx')],
            },
        ),
    ]
