# Generated by Django 5.2.8 on 2025-11-24 15:19

import django.db.models.deletion
from django.db import migrations, models


def migrate_to_foreign_keys(apps, schema_editor):
    """Migrate data from integer ID fields to ForeignKey fields"""
    Notification = apps.get_model('user_notifications', 'Notification')
    PurchaseRequest = apps.get_model('purchase_requests', 'PurchaseRequest')
    PurchaseOrder = apps.get_model('purchase_orders', 'PurchaseOrder')
    Receipt = apps.get_model('receipts', 'Receipt')
    
    db_alias = schema_editor.connection.alias
    
    for notification in Notification.objects.using(db_alias).all():
        updated = False
        
        # Migrate request_id to request ForeignKey
        if hasattr(notification, 'request_id') and notification.request_id:
            try:
                request = PurchaseRequest.objects.using(db_alias).get(id=notification.request_id)
                notification.request = request
                updated = True
            except PurchaseRequest.DoesNotExist:
                pass
        
        # Migrate po_id to purchase_order ForeignKey
        if hasattr(notification, 'po_id') and notification.po_id:
            try:
                po = PurchaseOrder.objects.using(db_alias).get(id=notification.po_id)
                notification.purchase_order = po
                updated = True
            except PurchaseOrder.DoesNotExist:
                pass
        
        # Migrate receipt_id to receipt ForeignKey
        if hasattr(notification, 'receipt_id') and notification.receipt_id:
            try:
                receipt = Receipt.objects.using(db_alias).get(id=notification.receipt_id)
                notification.receipt = receipt
                updated = True
            except Receipt.DoesNotExist:
                pass
        
        if updated:
            notification.save()


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0001_initial'),
        ('purchase_requests', '0004_remove_completed_status'),
        ('receipts', '0001_initial'),
        ('user_notifications', '0001_initial'),
    ]

    operations = [
        # Step 1: Add new ForeignKey fields
        migrations.AddField(
            model_name='notification',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='purchase_orders.purchaseorder'),
        ),
        migrations.AddField(
            model_name='notification',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='receipts.receipt'),
        ),
        migrations.AddField(
            model_name='notification',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='purchase_requests.purchaserequest'),
        ),
        # Step 2: Migrate data from integer fields to ForeignKeys
        migrations.RunPython(migrate_to_foreign_keys, migrations.RunPython.noop),
        # Step 3: Remove old integer ID fields
        migrations.RemoveField(
            model_name='notification',
            name='po_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='receipt_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='request_id',
        ),
    ]
