# Generated by Django 5.2.8 on 2025-11-24 15:19
# Modified to be idempotent and handle partial migration states

from django.db import migrations


def get_existing_columns(cursor):
    """Get set of existing column names for the notification table"""
    cursor.execute("""
        SELECT column_name
        FROM information_schema.columns
        WHERE table_name = 'user_notifications_notification'
    """)
    return {row[0] for row in cursor.fetchall()}


def check_and_rename_columns(apps, schema_editor):
    """
    Check if old integer columns exist and rename them.
    This handles the case where the migration partially ran before.
    """
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        existing_columns = get_existing_columns(cursor)

        # Rename columns if they exist (and not already renamed)
        renames = [
            ('request_id', 'old_request_id'),
            ('po_id', 'old_po_id'),
            ('receipt_id', 'old_receipt_id'),
        ]

        for old_name, new_name in renames:
            if old_name in existing_columns and new_name not in existing_columns:
                cursor.execute(
                    f'ALTER TABLE user_notifications_notification RENAME COLUMN "{old_name}" TO "{new_name}"'
                )


def add_fk_columns(apps, schema_editor):
    """Add ForeignKey columns if they don't already exist"""
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        existing_columns = get_existing_columns(cursor)

        # Add purchase_order_id if not exists
        if 'purchase_order_id' not in existing_columns:
            cursor.execute("""
                ALTER TABLE user_notifications_notification
                ADD COLUMN purchase_order_id BIGINT NULL
                REFERENCES purchase_orders_purchaseorder(id)
                ON DELETE SET NULL
            """)

        # Add receipt_id if not exists (after rename of old receipt_id to old_receipt_id)
        if 'receipt_id' not in existing_columns:
            cursor.execute("""
                ALTER TABLE user_notifications_notification
                ADD COLUMN receipt_id BIGINT NULL
                REFERENCES receipts_receipt(id)
                ON DELETE SET NULL
            """)

        # Add request_id if not exists (after rename of old request_id to old_request_id)
        if 'request_id' not in existing_columns:
            cursor.execute("""
                ALTER TABLE user_notifications_notification
                ADD COLUMN request_id BIGINT NULL
                REFERENCES purchase_requests_purchaserequest(id)
                ON DELETE SET NULL
            """)


def migrate_data(apps, schema_editor):
    """Migrate data from old integer columns to new FK columns using raw SQL"""
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        existing_columns = get_existing_columns(cursor)

        # Migrate old_request_id to request_id if both columns exist
        if 'old_request_id' in existing_columns and 'request_id' in existing_columns:
            cursor.execute("""
                UPDATE user_notifications_notification n
                SET request_id = n.old_request_id
                WHERE n.old_request_id IS NOT NULL
                AND EXISTS (SELECT 1 FROM purchase_requests_purchaserequest pr WHERE pr.id = n.old_request_id)
            """)

        # Migrate old_po_id to purchase_order_id if both columns exist
        if 'old_po_id' in existing_columns and 'purchase_order_id' in existing_columns:
            cursor.execute("""
                UPDATE user_notifications_notification n
                SET purchase_order_id = n.old_po_id
                WHERE n.old_po_id IS NOT NULL
                AND EXISTS (SELECT 1 FROM purchase_orders_purchaseorder po WHERE po.id = n.old_po_id)
            """)

        # Migrate old_receipt_id to receipt_id if both columns exist
        if 'old_receipt_id' in existing_columns and 'receipt_id' in existing_columns:
            cursor.execute("""
                UPDATE user_notifications_notification n
                SET receipt_id = n.old_receipt_id
                WHERE n.old_receipt_id IS NOT NULL
                AND EXISTS (SELECT 1 FROM receipts_receipt r WHERE r.id = n.old_receipt_id)
            """)


def remove_old_columns(apps, schema_editor):
    """Remove old integer columns if they exist"""
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        existing_columns = get_existing_columns(cursor)

        old_columns = ['old_request_id', 'old_po_id', 'old_receipt_id']

        for col in old_columns:
            if col in existing_columns:
                cursor.execute(
                    f'ALTER TABLE user_notifications_notification DROP COLUMN "{col}"'
                )


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0001_initial'),
        ('purchase_requests', '0004_remove_completed_status'),
        ('receipts', '0001_initial'),
        ('user_notifications', '0001_initial'),
    ]

    operations = [
        # Step 1: Rename old integer columns to avoid conflicts with new FK columns
        migrations.RunPython(check_and_rename_columns, migrations.RunPython.noop),
        # Step 2: Add new ForeignKey columns
        migrations.RunPython(add_fk_columns, migrations.RunPython.noop),
        # Step 3: Migrate data from old columns to new FK columns
        migrations.RunPython(migrate_data, migrations.RunPython.noop),
        # Step 4: Remove old columns
        migrations.RunPython(remove_old_columns, migrations.RunPython.noop),
    ]
