# Generated by Django 5.2.8 on 2025-11-23 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_requests', '0002_purchaserequest_document_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(help_text='Unique PO number in format PO-YYYYMMDD-XXXX', max_length=50, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when PO was generated')),
                ('pdf_file', models.CharField(blank=True, help_text='Cloudinary URL for the PO PDF', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(help_text='Associated purchase request', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='purchase_requests.purchaserequest')),
            ],
            options={
                'db_table': 'purchase_orders',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['po_number'], name='purchase_or_po_numb_656941_idx'), models.Index(fields=['-generated_at'], name='purchase_or_generat_2c6443_idx')],
            },
        ),
    ]
