# Generated by Django 5.2.8 on 2025-11-24 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('PURCHASE_ORDERS', 'Purchase Orders'), ('RECEIPTS', 'Receipts'), ('SPENDING_SUMMARY', 'Spending Summary'), ('APPROVAL_TIMELINE', 'Approval Timeline')], max_length=50)),
                ('export_format', models.CharField(choices=[('CSV', 'CSV'), ('PDF', 'PDF')], max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('filters_applied', models.JSONField(blank=True, default=dict)),
                ('record_count', models.IntegerField(default=0)),
                ('file_size_kb', models.IntegerField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_logs',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['user', '-generated_at'], name='export_logs_user_id_6643ac_idx'), models.Index(fields=['export_type'], name='export_logs_export__7d651f_idx')],
            },
        ),
    ]
